### ISSUE TITLE
Mismatch between JDK announcement and Dockerfile implementation

### ISSUE THREAD

**Issue by tverhoken** [markhobson/docker-node-chrome#1]
Hello,

In the description it is announced JDK8 but Dockerfile pull from openjdk 7.

**Comment by tverhoken** [comment]
I did the fix but i got "permission denied" when i try to push the branch with the fix.

What do i have to do to be able to push the fix ?

**Comment by markhobson** [comment]
Hi, good spot! Does your fix upgrade the image to Java 8 or correct the documentation to Java 7? I'd recommend the former.

To provide the fix, fork the repository and create a pull request for this issue. Check out the GitHub help docs for more info: https://help.github.com/articles/creating-a-pull-request-from-a-fork/ Thanks.
